export const crse_dept_array = [
  "Account, Fin, & Info Systems",
  "Anthro, Socio, and Social Work",
  "Applied Engineering & Tech Mgt",
  "Biological Sciences",
  "Communication",
  "Curriculum and Instruction",
  "Dept. of Safety & Security",
  "Ed Lead & Couns Ed & Comm Dis",
  "Exercise & Sport Science",
  "Geosciences",
  "Government & Economics",
  "Health Promotion & Admin",
  "History, Phi and Religious Stu",
  "Interdisciplinary Programs",
  "Mathematics & Statistics",
  "Mgt, Mrktng, & Intrntnl Bus",
  "Military Science & Leadership",
  "Office of Academic Affairs",
  "Psychology",
  "Recreation & Park Admin",
  "School of Justice Studies",
  "Agriculture",
  "Amer Sign Lang & Interptr Educ",
  "Applied Human Sciences",
  "Art and Design",
  "Chemistry",
  "College of Arts & Sciences",
  "College of Business & Tech",
  "College of Education",
  "College of Health Sciences",
  "College of Justice & Safety",
  "College of Ltrs, Arts, SocSci",
  "College of Science",
  "Computer Science",
  "Criminal Just & Police Studies",
  "English and Theatre",
  "Environ Health & Clinical Lab",
  "Fire Protection & Paramed Sci",
  "Languages, Cultures,Humanities",
  "Medical Laboratory Science",
  "Music",
  "Nursing (Associate)",
  "Nursing (Bacc & Graduate)",
  "Occupational Therapy",
  "Physics and Astronomy",
  "School of Business",
  "School of Music",
  "University Programs",
  "Family and Consumer Sciences",
  "Honors Program",
  "Ed Leadership & Counselor Ed",
  "COSD",
  "Communication Sci & Disorders",
  "School of Nursing",
  "Clinical Therapeutic Programs",
  "College of Ed & App Human Sci",
  "College of Just, Sfty, Mil Sci",
  "College of STEM",
  "Computer Sci & Info Tech",
  "English",
  "Lang & Culture, Anthro, & Soc",
  "Physics, Geosci & Astronomy",
  "Social Work",
  "Teach, Learn & Edu Leadership",
  "Government",
  "Public Health and Clinical Sci",
  "Parks, Rec, Exer, & Sport Sci",
  "School of Eng, Avia, Cons, Tec",
  "Agri, Nat Resources, & Environ",
  "Chemistry & Forensic Science",
  "School of Aviation",
  "School of SSEM",
];
