export const instructional_mode_array = [
  "ALE - Applied Learning Experience",
  "ONL - Online: 100%",
  "TRD - Traditional class:face-to-face",
  "WBL - Web-blended:onl & face-to-face",
  " ",
  "DUL - Dual Credit: high school",
  "ITV - E-Presence:Telepresence course",
  "MMD - Mixed Mode",
  "ONL - 100% Online: Asynchronous",
  "TRD - Traditional Face-to-Face",
  "WBL - Web-blended: Asynchronous",
  "HYBR - Hybrid F2F Staggered/Remote",
  "ONLS - 100% Online: Synchronous",
  "WBLS - Web-blended: Synchronous",
  "ITV - ITV Telepresence course",
  "ONL - 100 pct Online: Asynchronous",
  "ONLS - 100 pct Online: Synchronous",
  "EPRES - E-Presence",
];
