export const schedule_type_array = [
  "1 - LEC    Lecture",
  "8 - SPE      Special",
  "C - COOP   Cooperative Education",
  "I - INTN     Internship",
  "L - L/LB    Lecture w/Lab included",
  "0 - LABO Lab:graded w/cr hrs",
  "2 - LAB    Lab:no grade/no cr hrs",
  "3 - IND    Independent Study-Prob",
  "4 - MUSC   Applied Music",
  "5 - STDO   Studio Course",
  "6 - PE        Activity Course",
  "9 - THES    Thesis or Dissertation",
  "CL - Clinical lab experience",
  "D - DUAL  Dual Credit for H S",
  "EX - Exit Exam- Graduation Reqrmnt",
  "P - PRAC     Practicum",
  "S - SEM  Seminar",
  "W - WEB  Blended= Class + >70% WEB",
  "B - WEB     Online 100%",
  "Q - COLQ Colloquium/Discussion",
  "T - ITV     Interactive Telecourse",
  "D - Dual Credit",
];
